### ISSUE TITLE
关于这个focal loss和那个分类器一起使用

### ISSUE THREAD

**Issue by zwd13122889** [HeyLynne/FocalLoss_for_multiclass#2]
softmax还是crf

**Comment by HeyLynne** [comment]
softmax是分类的，你要是有其他需求可以加crf.这个是根据自己的需求和目的来的






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HeyLynne/FocalLoss_for_multiclass"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 下午5:12
收件人:&nbsp;"HeyLynne/FocalLoss_for_multiclass"<FocalLoss_for_multiclass@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HeyLynne/FocalLoss_for_multiclass] 关于这个focal loss和那个分类器一起使用 (#2)





 
softmax还是crf

**Comment by zwd13122889** [comment]
> 其他需求可以加crf.这个是根据

非常感谢。我还想问下，正常的crf损失函数用的是最大似然，focal loss 相当于取代了他的最大似然，是吧

**Comment by HeyLynne** [comment]
> > 其他需求可以加crf.这个是根据
> 
> 非常感谢。我还想问下，正常的crf损失函数用的是最大似然，focal loss 相当于取代了他的最大似然，是吧

这个建议自己阅读crf的原理，并且自己试验
